namespace Platform.Domain;

/// <summary>
/// Publication status of a Curriculum (Curriculum Aggregate Design).
/// A Curriculum is the pedagogical shape of a Learning Product; its own
/// publication is distinct from the Product's (Learning Product §16).
/// </summary>
public enum CurriculumStatus { Draft, Published, Archived }

/// <summary>
/// Publication status of a Lesson — its business identity, not its content
/// (Lesson Aggregate Design §19: identity and publication live here, while
/// instructional content and its evolution live on Lesson Revision).
/// </summary>
public enum LessonStatus { Draft, Published, Archived }

/// <summary>
/// Status of one Lesson Revision. Revisions are the unit of authoring: a
/// published Lesson keeps serving its current revision while the next one is
/// still being written.
/// </summary>
public enum LessonRevisionStatus { Draft, Published, Superseded }

/// <summary>
/// How a Lesson is delivered — recorded content a learner works through on
/// their own, a live session the tutor runs (Learning Product Aggregate
/// Design's Instructor-Led pacing: "usually in live sessions arranged with
/// that learner"), or a self-paced document-based lesson with no video at
/// all (<see cref="Reading"/>). Descriptive only, exactly like Pacing Model:
/// it records the tutor's intent and enforces nothing by itself — Scheduling
/// Context, which would act on <see cref="LiveSession"/> (booking, calendar,
/// a join link), is not built yet.
/// </summary>
public enum LessonDeliveryMode
{
    Recorded,
    LiveSession,

    /// <summary>
    /// A self-paced lesson built from text/PDF/image content, no video
    /// required to publish (unlike <see cref="Recorded"/>) and no live
    /// component implied (unlike <see cref="LiveSession"/>). A lesson may
    /// still carry an optional illustrative video under this mode — Reading
    /// only changes what's required to publish, the same relationship
    /// LiveSession already has to its own optional recording.
    /// </summary>
    Reading
}

/// <summary>
/// Where a Lesson Revision's AI-generated transcript stands.
/// None -&gt; Processing -&gt; Ready | Failed. A fresh Processing attempt after
/// Failed goes back to Processing — there is no separate "retry" state.
/// </summary>
public enum TranscriptStatus { None, Processing, Ready, Failed }

/// <summary>
/// How the transcript was provided: generated by AI (Automatic), typed directly
/// by the tutor (Manual), or imported from an external source.
/// </summary>
public enum TranscriptSource { None, Automatic, Manual, Imported }

/// <summary>
/// Where a Lesson Revision's AI transcript enhancement stands. Independent of
/// <see cref="TranscriptStatus"/> — the raw transcript can be Ready while its
/// enhancement is None, Processing, Failed, or successfully Ready/ReviewRequired.
/// ReviewRequired is a distinct terminal state from Ready: the enhanced text was
/// produced and is saved (so a tutor can read it), but the conservative
/// preservation checks found something — a changed number, an uncertain segment,
/// a self-reported preservation-check failure — that means it should not be
/// treated as a clean, silent replacement candidate without a human look.
/// </summary>
public enum EnhancementStatus { None, Processing, Ready, ReviewRequired, Failed }
