using Microsoft.EntityFrameworkCore;
using Platform.Domain;

namespace Platform.Infrastructure;

/// <summary>
/// EF Core DbContext for the Platform.
/// Connection string is injected by .NET Aspire service discovery
/// via the "PlatformDB" resource name configured in Platform.AppHost.
/// </summary>
public class PlatformDbContext : DbContext
{
    public PlatformDbContext(DbContextOptions<PlatformDbContext> options) : base(options) { }

    public DbSet<Identity> Identities => Set<Identity>();
    public DbSet<Workspace> Workspaces => Set<Workspace>();
    public DbSet<Membership> Memberships => Set<Membership>();
    public DbSet<Invitation> Invitations => Set<Invitation>();
    public DbSet<PlatformOperator> PlatformOperators => Set<PlatformOperator>();
    public DbSet<JoinRequest> JoinRequests => Set<JoinRequest>();
    public DbSet<SignupRequest> SignupRequests => Set<SignupRequest>();
    public DbSet<LearningProduct> LearningProducts => Set<LearningProduct>();
    public DbSet<Curriculum> Curricula => Set<Curriculum>();
    public DbSet<Lesson> Lessons => Set<Lesson>();
    public DbSet<LearningAsset> LearningAssets => Set<LearningAsset>();
    public DbSet<Assessment> Assessments => Set<Assessment>();
    public DbSet<Enrollment> Enrollments => Set<Enrollment>();
    public DbSet<Submission> Submissions => Set<Submission>();
    public DbSet<LessonProgress> LessonProgresses => Set<LessonProgress>();
    public DbSet<Notification> Notifications => Set<Notification>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Identity>(entity =>
        {
            entity.ToTable("identities");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Email)
                  .IsRequired()
                  .HasMaxLength(256);

            // INV-002: Identity is globally unique — enforce at DB level
            entity.HasIndex(e => e.Email).IsUnique();

            entity.Property(e => e.PasswordHash)
                  .IsRequired();

            entity.Property(e => e.FullName)
                  .IsRequired()
                  .HasMaxLength(256);

            // Store enums as readable strings (not integers)
            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);
        });

        modelBuilder.Entity<Workspace>(entity =>
        {
            entity.ToTable("workspaces");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Name)
                  .IsRequired()
                  .HasMaxLength(256);

            entity.Property(e => e.Slug)
                  .IsRequired()
                  .HasMaxLength(128);

            // Public identifier resolves to exactly one Workspace (INV-006 in spirit —
            // the Entry Point Registry proper is not yet implemented, see TD-006)
            entity.HasIndex(e => e.Slug).IsUnique();

            entity.Property(e => e.Description)
                  .HasMaxLength(2048);

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            // Ownership Record → Owner MembershipId. Intentionally NOT a foreign key:
            // Workspace and Membership reference each other, and Workspace Aggregate
            // Design Section 17 requires reference-by-identifier only.
            entity.Property(e => e.OwnerMembershipId);
        });

        modelBuilder.Entity<Membership>(entity =>
        {
            entity.ToTable("memberships");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.IdentityId).IsRequired();
            entity.Property(e => e.WorkspaceId).IsRequired();

            // A person holds at most one Membership per Workspace
            entity.HasIndex(e => new { e.IdentityId, e.WorkspaceId }).IsUnique();

            // Lookup path for "which Workspaces does this Identity belong to?"
            entity.HasIndex(e => e.IdentityId);

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            // Roles are an entity collection of this aggregate, reached through the
            // private _roles backing field rather than the read-only Roles property.
            entity.HasMany(e => e.Roles)
                  .WithOne()
                  .HasForeignKey(r => r.MembershipId)
                  .OnDelete(DeleteBehavior.Cascade);

            entity.Navigation(e => e.Roles)
                  .UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<Invitation>(entity =>
        {
            entity.ToTable("invitations");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();

            entity.Property(e => e.Email)
                  .IsRequired()
                  .HasMaxLength(256);

            // Validation looks an invitation up by token hash on every link visit
            entity.Property(e => e.TokenHash)
                  .IsRequired()
                  .HasMaxLength(64);
            entity.HasIndex(e => e.TokenHash).IsUnique();

            // The admin's provisioning view lists invitations per Workspace, and
            // the single-active-invitation check queries by (email, workspace)
            entity.HasIndex(e => e.WorkspaceId);
            entity.HasIndex(e => new { e.Email, e.WorkspaceId });

            entity.Property(e => e.IntendedRole)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);
        });

        modelBuilder.Entity<JoinRequest>(entity =>
        {
            entity.ToTable("join_requests");

            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.IdentityId).IsRequired();

            entity.Property(e => e.Email)
                  .IsRequired()
                  .HasMaxLength(256);

            entity.Property(e => e.FullName)
                  .IsRequired()
                  .HasMaxLength(256);

            entity.Property(e => e.Message)
                  .HasMaxLength(2000);

            entity.Property(e => e.RequestedRole)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            // The reviewer's queue reads by Workspace; the single-open-request
            // check reads by (identity, workspace)
            entity.HasIndex(e => e.WorkspaceId);
            entity.HasIndex(e => new { e.IdentityId, e.WorkspaceId });
        });

        modelBuilder.Entity<SignupRequest>(entity =>
        {
            entity.ToTable("signup_requests");

            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.FullName).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Email).IsRequired().HasMaxLength(256);
            entity.Property(e => e.About).HasMaxLength(2000);
            entity.Property(e => e.RejectionReason).HasMaxLength(2000);

            // Every status-link visit looks the application up by token hash
            // Nullable: the hash is cleared when the status link is revoked, so a
            // spent token stops resolving entirely. Postgres permits many NULLs
            // under a unique index, which is exactly what retired links need.
            entity.Property(e => e.TokenHash).HasMaxLength(64);
            entity.HasIndex(e => e.TokenHash).IsUnique();

            // The admin queue reads by status; the duplicate check reads by email
            entity.HasIndex(e => e.Status);
            entity.HasIndex(e => e.Email);

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            entity.Property(e => e.Payment)
                  .HasConversion<string>()
                  .HasMaxLength(32);
        });

        modelBuilder.Entity<LearningProduct>(entity =>
        {
            entity.ToTable("learning_products");

            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.CreatedByMembershipId).IsRequired();

            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Description).HasMaxLength(4000);
            entity.Property(e => e.Category).HasMaxLength(128);
            entity.Property(e => e.DefaultLanguage).HasMaxLength(32);

            // Tags are a small ordered list owned entirely by this aggregate;
            // a join table would add a query for no benefit at this size.
            entity.PrimitiveCollection(e => e.Tags);

            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.Pacing).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.EnrollmentMode).HasConversion<string>().HasMaxLength(32);

            // Every listing is scoped to one workspace (INV-001)
            entity.HasIndex(e => e.WorkspaceId);
        });

        modelBuilder.Entity<Curriculum>(entity =>
        {
            entity.ToTable("curricula");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.LearningProductId).IsRequired();
            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // INV-003 (Learning Product): at most one active Curriculum per product,
            // so every read is by product
            entity.HasIndex(e => e.LearningProductId);

            entity.HasMany(e => e.Units).WithOne()
                  .HasForeignKey(u => u.CurriculumId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Units).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<CurriculumUnit>(entity =>
        {
            entity.ToTable("curriculum_units");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);

            entity.HasMany(e => e.Lessons).WithOne()
                  .HasForeignKey(l => l.UnitId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Lessons).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<CurriculumLesson>(entity =>
        {
            entity.ToTable("curriculum_lessons");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            // A lesson appears at most once in a given unit
            entity.HasIndex(e => new { e.UnitId, e.LessonId }).IsUnique();
        });

        modelBuilder.Entity<Lesson>(entity =>
        {
            entity.ToTable("lessons");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.LearningProductId).IsRequired();
            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);
            entity.HasIndex(e => e.LearningProductId);

            entity.HasMany(e => e.Revisions).WithOne()
                  .HasForeignKey(r => r.LessonId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Revisions).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<LessonRevision>(entity =>
        {
            entity.ToTable("lesson_revisions");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);
            // Version numbers are unique per lesson and never reused
            entity.HasIndex(e => new { e.LessonId, e.Version }).IsUnique();

            // Reference by identifier only (Learning Asset Aggregate Design INV-003) —
            // deliberately not a foreign key, matching Workspace.OwnerMembershipId
            // above: the two aggregates evolve independently.
            entity.Property(e => e.VideoAssetId);
            entity.Property(e => e.VideoUrl).HasMaxLength(2048);

            entity.Property(e => e.DeliveryMode).HasConversion<string>().HasMaxLength(32);
        });

        modelBuilder.Entity<LearningAsset>(entity =>
        {
            entity.ToTable("learning_assets");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.UploadedByMembershipId).IsRequired();

            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.OriginalFileName).IsRequired().HasMaxLength(512);
            entity.Property(e => e.ContentType).IsRequired().HasMaxLength(128);
            entity.Property(e => e.StorageProvider).IsRequired().HasMaxLength(32);
            entity.Property(e => e.ObjectKey).IsRequired().HasMaxLength(1024);

            entity.Property(e => e.Category).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // The picker in Content Studio lists every asset in the Workspace
            entity.HasIndex(e => e.WorkspaceId);
        });

        modelBuilder.Entity<Assessment>(entity =>
        {
            entity.ToTable("assessments");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.LessonId).IsRequired();
            entity.Property(e => e.LessonRevisionId).IsRequired();
            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // One interactive-quiz Assessment per Lesson Revision (Assessment.cs
            // remarks) — LessonId is a denormalized convenience, not unique.
            entity.HasIndex(e => e.LessonRevisionId).IsUnique();

            entity.HasMany(e => e.Questions).WithOne()
                  .HasForeignKey(q => q.AssessmentId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Questions).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.ToTable("assessment_questions");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Prompt).IsRequired().HasMaxLength(2000);
            entity.Property(e => e.Explanation).HasMaxLength(2000);
            entity.Property(e => e.Type).HasConversion<string>().HasMaxLength(32);

            // Small ordered lists owned entirely by this entity — same
            // reasoning as LearningProduct.Tags above, a join table buys nothing.
            // Only one of the two is populated, depending on Type (Question.Apply).
            entity.PrimitiveCollection(e => e.Options);
            entity.PrimitiveCollection(e => e.AcceptedAnswers);
        });

        modelBuilder.Entity<Enrollment>(entity =>
        {
            entity.ToTable("enrollments");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.LearningProductId).IsRequired();
            entity.Property(e => e.MembershipId).IsRequired();

            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // Auto-created on first open (Enrollment.cs remarks) — at most one per (product, membership)
            entity.HasIndex(e => new { e.LearningProductId, e.MembershipId }).IsUnique();
        });

        modelBuilder.Entity<Submission>(entity =>
        {
            entity.ToTable("submissions");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.AssessmentId).IsRequired();
            entity.Property(e => e.MembershipId).IsRequired();
            entity.Property(e => e.EnrollmentId).IsRequired();

            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // A learner's attempts at one assessment are read together for "latest attempt"
            entity.HasIndex(e => new { e.AssessmentId, e.MembershipId });

            entity.HasMany(e => e.Answers).WithOne()
                  .HasForeignKey(a => a.SubmissionId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Answers).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<SubmissionAnswer>(entity =>
        {
            entity.ToTable("submission_answers");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.QuestionId).IsRequired();
            entity.Property(e => e.TextAnswer).HasMaxLength(2000);
        });

        modelBuilder.Entity<LessonProgress>(entity =>
        {
            entity.ToTable("lesson_progress");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.EnrollmentId).IsRequired();
            entity.Property(e => e.LessonId).IsRequired();

            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // One progress row per (enrollment, lesson)
            entity.HasIndex(e => new { e.EnrollmentId, e.LessonId }).IsUnique();
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.ToTable("notifications");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.MembershipId).IsRequired();
            entity.Property(e => e.LessonId).IsRequired();
            entity.Property(e => e.Title).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Message).IsRequired().HasMaxLength(2000);
            entity.Property(e => e.Kind).HasConversion<string>().HasMaxLength(64);

            // A learner's own inbox, newest first, and "how many unread" — both read together
            entity.HasIndex(e => new { e.MembershipId, e.CreatedAt });
        });

        modelBuilder.Entity<PlatformOperator>(entity =>
        {
            entity.ToTable("platform_operators");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.IdentityId).IsRequired();

            // Every authorized admin request resolves the caller's grant by IdentityId
            entity.HasIndex(e => e.IdentityId);

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);
        });

        modelBuilder.Entity<WorkspaceRole>(entity =>
        {
            entity.ToTable("workspace_roles");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Name)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            // A Membership holds a given role at most once
            entity.HasIndex(e => new { e.MembershipId, e.Name }).IsUnique();
        });
    }
}
