using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Platform.Domain;

namespace Platform.Infrastructure;

/// <summary>
/// EF Core DbContext for the Platform.
/// Connection string is injected by .NET Aspire service discovery
/// via the "PlatformDB" resource name configured in Platform.AppHost.
/// </summary>
public class PlatformDbContext : DbContext
{
    public PlatformDbContext(DbContextOptions<PlatformDbContext> options) : base(options) { }

    public DbSet<Identity> Identities => Set<Identity>();
    public DbSet<Workspace> Workspaces => Set<Workspace>();
    public DbSet<Membership> Memberships => Set<Membership>();
    public DbSet<Invitation> Invitations => Set<Invitation>();
    public DbSet<InvitationBatch> InvitationBatches => Set<InvitationBatch>();
    public DbSet<PasswordReset> PasswordResets => Set<PasswordReset>();
    public DbSet<PlatformOperator> PlatformOperators => Set<PlatformOperator>();
    public DbSet<JoinRequest> JoinRequests => Set<JoinRequest>();
    public DbSet<CourseJoinRequest> CourseJoinRequests => Set<CourseJoinRequest>();
    public DbSet<SignupRequest> SignupRequests => Set<SignupRequest>();
    public DbSet<LearningProduct> LearningProducts => Set<LearningProduct>();
    public DbSet<Curriculum> Curricula => Set<Curriculum>();
    public DbSet<Lesson> Lessons => Set<Lesson>();
    public DbSet<LearningAsset> LearningAssets => Set<LearningAsset>();
    public DbSet<LessonResource> LessonResources => Set<LessonResource>();
    public DbSet<Assessment> Assessments => Set<Assessment>();
    public DbSet<LearningActivity> LearningActivities => Set<LearningActivity>();
    public DbSet<Assignment> Assignments => Set<Assignment>();
    public DbSet<Enrollment> Enrollments => Set<Enrollment>();
    public DbSet<Submission> Submissions => Set<Submission>();
    public DbSet<LessonProgress> LessonProgresses => Set<LessonProgress>();
    public DbSet<Notification> Notifications => Set<Notification>();

    // ── Commercial Domain — core spine (V1a) ────────────────────────────────
    public DbSet<ConfigurationSnapshot> ConfigurationSnapshots => Set<ConfigurationSnapshot>();
    public DbSet<Subscription> Subscriptions => Set<Subscription>();
    public DbSet<SubscriptionEvent> SubscriptionEvents => Set<SubscriptionEvent>();
    public DbSet<WorkspaceLicense> WorkspaceLicenses => Set<WorkspaceLicense>();
    public DbSet<EntitlementOverride> EntitlementOverrides => Set<EntitlementOverride>();
    public DbSet<BillingAccount> BillingAccounts => Set<BillingAccount>();
    public DbSet<Invoice> Invoices => Set<Invoice>();

    // ── Commercial Domain — catalog (Products/Packs, database-backed) ───────
    public DbSet<ProductFamily> ProductFamilies => Set<ProductFamily>();
    public DbSet<CommercialProduct> CommercialProducts => Set<CommercialProduct>();
    public DbSet<CommercialProductVersion> CommercialProductVersions => Set<CommercialProductVersion>();
    public DbSet<CommercialPack> CommercialPacks => Set<CommercialPack>();
    public DbSet<CommercialPackVersion> CommercialPackVersions => Set<CommercialPackVersion>();

    // ── Commercial Domain — AI Credit Ledger ─────────────────────────────────
    public DbSet<CreditLedgerEntry> CreditLedgerEntries => Set<CreditLedgerEntry>();
    public DbSet<SkillCreditCost> SkillCreditCosts => Set<SkillCreditCost>();
    public DbSet<CreditPurchaseOrder> CreditPurchaseOrders => Set<CreditPurchaseOrder>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Identity>(entity =>
        {
            entity.ToTable("identities");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Email)
                  .IsRequired()
                  .HasMaxLength(256);

            // INV-002: Identity is globally unique — enforce at DB level
            entity.HasIndex(e => e.Email).IsUnique();

            entity.Property(e => e.PasswordHash)
                  .IsRequired();

            entity.Property(e => e.FullName)
                  .IsRequired()
                  .HasMaxLength(256);

            // Store enums as readable strings (not integers)
            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);
        });

        modelBuilder.Entity<Workspace>(entity =>
        {
            entity.ToTable("workspaces");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Name)
                  .IsRequired()
                  .HasMaxLength(256);

            entity.Property(e => e.Slug)
                  .IsRequired()
                  .HasMaxLength(128);

            // Public identifier resolves to exactly one Workspace (INV-006 in spirit —
            // the Entry Point Registry proper is not yet implemented, see TD-006)
            entity.HasIndex(e => e.Slug).IsUnique();

            entity.Property(e => e.Description)
                  .HasMaxLength(2048);

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            // Ownership Record → Owner MembershipId. Intentionally NOT a foreign key:
            // Workspace and Membership reference each other, and Workspace Aggregate
            // Design Section 17 requires reference-by-identifier only.
            entity.Property(e => e.OwnerMembershipId);

            // Branding — reference-by-identifier, same convention as OwnerMembershipId above.
            entity.Property(e => e.LogoAssetId);
            entity.Property(e => e.WelcomeMessage).HasMaxLength(2048);
            entity.PrimitiveCollection(e => e.CourseCategories);
        });

        modelBuilder.Entity<Membership>(entity =>
        {
            entity.ToTable("memberships");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.IdentityId).IsRequired();
            entity.Property(e => e.WorkspaceId).IsRequired();

            // A person holds at most one Membership per Workspace
            entity.HasIndex(e => new { e.IdentityId, e.WorkspaceId }).IsUnique();

            // Lookup path for "which Workspaces does this Identity belong to?"
            entity.HasIndex(e => e.IdentityId);

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            // Roles are an entity collection of this aggregate, reached through the
            // private _roles backing field rather than the read-only Roles property.
            entity.HasMany(e => e.Roles)
                  .WithOne()
                  .HasForeignKey(r => r.MembershipId)
                  .OnDelete(DeleteBehavior.Cascade);

            entity.Navigation(e => e.Roles)
                  .UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<Invitation>(entity =>
        {
            entity.ToTable("invitations");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();

            entity.Property(e => e.Email)
                  .IsRequired()
                  .HasMaxLength(256);

            // Validation looks an invitation up by token hash on every link visit
            entity.Property(e => e.TokenHash)
                  .IsRequired()
                  .HasMaxLength(64);
            entity.HasIndex(e => e.TokenHash).IsUnique();

            // The admin's provisioning view lists invitations per Workspace, and
            // the single-active-invitation check queries by (email, workspace)
            entity.HasIndex(e => e.WorkspaceId);

            // §8: at most one open (Sent) Invitation per (email, workspace) —
            // previously enforced only in WorkspaceMemberService.InviteAsync's
            // application-level check, a plain check-then-act race under
            // concurrent invite requests for the same email. WorkspaceMemberService
            // now promotes a time-expired Sent row to Expired status before this
            // check runs, which is what lets this filter see only genuinely open
            // invitations — the filter itself can only see Status, not the clock.
            entity.HasIndex(e => new { e.Email, e.WorkspaceId })
                  .IsUnique()
                  .HasFilter("\"Status\" = 'Sent'");

            entity.Property(e => e.IntendedRole)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            // §4.3: Invitation Batch groups Invitations by identifier only —
            // no FK, matching Workspace.OwnerMembershipId's cross-aggregate
            // reference convention. Indexed for the read-time rollup query.
            entity.Property(e => e.BatchId);
            entity.HasIndex(e => e.BatchId);

            // §12.3: reference by identifier only, same convention — read
            // back at acceptance time to decide whether to create an
            // Enrollment alongside the new Membership.
            entity.Property(e => e.IntendedLearningProductId);
        });

        modelBuilder.Entity<InvitationBatch>(entity =>
        {
            entity.ToTable("invitation_batches");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.CreatedBy).IsRequired();

            // Operational-visibility listing per Workspace (§4.3)
            entity.HasIndex(e => e.WorkspaceId);

            entity.Property(e => e.Source)
                  .HasConversion<string>()
                  .HasMaxLength(32);
        });

        modelBuilder.Entity<PasswordReset>(entity =>
        {
            entity.ToTable("password_resets");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.IdentityId).IsRequired();

            // Every link visit looks the reset up by token hash
            entity.Property(e => e.TokenHash)
                  .IsRequired()
                  .HasMaxLength(64);
            entity.HasIndex(e => e.TokenHash).IsUnique();

            // "Is there already an open reset for this Identity?" — checked
            // every time one is requested, so a fresher request can supersede it
            entity.HasIndex(e => e.IdentityId);

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);
        });

        modelBuilder.Entity<JoinRequest>(entity =>
        {
            entity.ToTable("join_requests");

            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();

            entity.Property(e => e.Email)
                  .IsRequired()
                  .HasMaxLength(256);

            entity.Property(e => e.FullName)
                  .IsRequired()
                  .HasMaxLength(256);

            entity.Property(e => e.Message)
                  .HasMaxLength(2000);

            entity.Property(e => e.RequestedRole)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            entity.Property(e => e.TokenHash).HasMaxLength(64);
            entity.HasIndex(e => e.TokenHash).IsUnique();

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            // The reviewer's queue reads by Workspace; the single-open-request
            // check reads by (email, workspace). §10: at most one Submitted
            // request per (email, workspace) — previously enforced only in
            // JoinRequestService.SubmitAsync's application-level check, a
            // plain check-then-act race under concurrent submissions.
            entity.HasIndex(e => e.WorkspaceId);
            entity.HasIndex(e => new { e.Email, e.WorkspaceId })
                  .IsUnique()
                  .HasFilter("\"Status\" = 'Submitted'");
        });

        modelBuilder.Entity<SignupRequest>(entity =>
        {
            entity.ToTable("signup_requests");

            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.FullName).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Email).IsRequired().HasMaxLength(256);
            entity.Property(e => e.About).HasMaxLength(2000);
            entity.Property(e => e.RejectionReason).HasMaxLength(2000);

            // Every status-link visit looks the application up by token hash
            // Nullable: the hash is cleared when the status link is revoked, so a
            // spent token stops resolving entirely. Postgres permits many NULLs
            // under a unique index, which is exactly what retired links need.
            entity.Property(e => e.TokenHash).HasMaxLength(64);
            entity.HasIndex(e => e.TokenHash).IsUnique();

            // The admin queue reads by status; the duplicate check reads by email
            entity.HasIndex(e => e.Status);
            entity.HasIndex(e => e.Email);

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);
        });

        modelBuilder.Entity<LearningProduct>(entity =>
        {
            entity.ToTable("learning_products");

            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.CreatedByMembershipId).IsRequired();

            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Description).HasMaxLength(4000);
            entity.Property(e => e.Category).HasMaxLength(128);
            entity.Property(e => e.DefaultLanguage).HasMaxLength(32);

            // Tags are a small ordered list owned entirely by this aggregate;
            // a join table would add a query for no benefit at this size.
            entity.PrimitiveCollection(e => e.Tags);

            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.Pacing).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.EnrollmentMode).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.CoverImageAssetId);

            // Every listing is scoped to one workspace (INV-001)
            entity.HasIndex(e => e.WorkspaceId);
        });

        modelBuilder.Entity<Curriculum>(entity =>
        {
            entity.ToTable("curricula");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.LearningProductId).IsRequired();
            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.RequiresSequentialCompletion).IsRequired().HasDefaultValue(false);

            // INV-003 (Learning Product): at most one active Curriculum per product,
            // so every read is by product. Enforced here, not just assumed —
            // MutateAsync's lazy-create (load-if-missing-then-add) is a
            // check-then-act race under concurrent requests for the same
            // product; this constraint is what actually stops a second row,
            // turning the loser of that race into a Conflict instead of
            // silent duplicate data.
            entity.HasIndex(e => e.LearningProductId)
                  .IsUnique()
                  .HasFilter("\"Status\" != 'Archived'");

            entity.HasMany(e => e.Units).WithOne()
                  .HasForeignKey(u => u.CurriculumId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Units).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<CurriculumUnit>(entity =>
        {
            entity.ToTable("curriculum_units");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);

            entity.HasMany(e => e.Lessons).WithOne()
                  .HasForeignKey(l => l.UnitId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Lessons).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<CurriculumLesson>(entity =>
        {
            entity.ToTable("curriculum_lessons");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            // A lesson appears at most once in a given unit
            entity.HasIndex(e => new { e.UnitId, e.LessonId }).IsUnique();
        });

        modelBuilder.Entity<Lesson>(entity =>
        {
            entity.ToTable("lessons");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.LearningProductId).IsRequired();
            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);
            entity.HasIndex(e => e.LearningProductId);

            entity.HasMany(e => e.Revisions).WithOne()
                  .HasForeignKey(r => r.LessonId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Revisions).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<LessonRevision>(entity =>
        {
            entity.ToTable("lesson_revisions");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);
            // Version numbers are unique per lesson and never reused
            entity.HasIndex(e => new { e.LessonId, e.Version }).IsUnique();

            // Reference by identifier only (Learning Asset Aggregate Design INV-003) —
            // deliberately not a foreign key, matching Workspace.OwnerMembershipId
            // above: the two aggregates evolve independently.
            entity.Property(e => e.VideoAssetId);
            entity.Property(e => e.VideoUrl).HasMaxLength(2048);

            entity.Property(e => e.DeliveryMode).HasConversion<string>().HasMaxLength(32);

            entity.Property(e => e.TranscriptStatus).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.TranscriptSource).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.TranscriptError).HasMaxLength(2000);

            entity.Property(e => e.WhatYoullLearn).HasMaxLength(1000);

            entity.Property(e => e.RequireQuizToComplete).IsRequired().HasDefaultValue(false);

            entity.HasMany(e => e.Resources).WithOne()
                  .HasForeignKey(r => r.LessonRevisionId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Resources).UsePropertyAccessMode(PropertyAccessMode.Field);

            entity.HasMany(e => e.LearningActivities).WithOne()
                  .HasForeignKey(a => a.LessonRevisionId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.LearningActivities).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<LearningActivity>(entity =>
        {
            entity.ToTable("learning_activities");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.LessonRevisionId).IsRequired();
            entity.Property(e => e.Type).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Instructions).HasMaxLength(4000);

            // Meaningful only for Type == Quiz/QuestionSet — reference by
            // identifier only, same convention as LessonRevision.VideoAssetId.
            entity.Property(e => e.AssessmentId);
            entity.Property(e => e.ExternalUrl).HasMaxLength(2048);

            entity.HasIndex(e => e.LessonRevisionId);
        });

        modelBuilder.Entity<Assignment>(entity =>
        {
            entity.ToTable("assignments");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            // Denormalized cross-aggregate references, no real FK — same
            // convention as Assessment.LessonId/LessonRevisionId above.
            entity.Property(e => e.LearningActivityId).IsRequired();
            entity.Property(e => e.LearningProductId).IsRequired();
            entity.Property(e => e.CreatorMembershipId).IsRequired();

            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.AvailabilityMode).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.DueDateMode).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.AttemptMode).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.EvaluationMethod).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.Configured).IsRequired().HasDefaultValue(false);

            // INV-002: 1:1 Learning Activity ↔ Assignment in V1.
            entity.HasIndex(e => e.LearningActivityId).IsUnique();
            // Tutor dashboard / recipient-resolution queries.
            entity.HasIndex(e => e.LearningProductId);
        });

        modelBuilder.Entity<LessonResource>(entity =>
        {
            entity.ToTable("lesson_resources");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.LessonRevisionId).IsRequired();
            // Reference by identifier only (Learning Asset Aggregate Design
            // INV-003), same reasoning as LessonRevision.VideoAssetId above —
            // deliberately not a foreign key.
            entity.Property(e => e.LearningAssetId).IsRequired();

            // Every resource attached before this flag existed behaves as
            // though it were true — the only behavior possible until now.
            entity.Property(e => e.VisibleToLearners).IsRequired().HasDefaultValue(true);

            entity.HasIndex(e => e.LessonRevisionId);
        });

        modelBuilder.Entity<LearningAsset>(entity =>
        {
            entity.ToTable("learning_assets");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.UploadedByMembershipId).IsRequired();

            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.OriginalFileName).IsRequired().HasMaxLength(512);
            entity.Property(e => e.ContentType).IsRequired().HasMaxLength(128);
            entity.Property(e => e.StorageProvider).IsRequired().HasMaxLength(32);
            entity.Property(e => e.ObjectKey).IsRequired().HasMaxLength(1024);

            entity.Property(e => e.Category).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // The picker in Content Studio lists every asset in the Workspace
            entity.HasIndex(e => e.WorkspaceId);
        });

        modelBuilder.Entity<Assessment>(entity =>
        {
            entity.ToTable("assessments");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.LessonId).IsRequired();
            entity.Property(e => e.LessonRevisionId).IsRequired();
            entity.Property(e => e.Title).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.Kind).HasConversion<string>().HasMaxLength(32);

            // At most one Assessment per (Lesson Revision, Kind) — a revision
            // may carry one Interactive and one Standalone Assessment side by
            // side (Assessment.cs remarks), but never two of the same kind.
            // LessonId is a denormalized convenience, not unique.
            entity.HasIndex(e => new { e.LessonRevisionId, e.Kind }).IsUnique();

            entity.HasMany(e => e.Questions).WithOne()
                  .HasForeignKey(q => q.AssessmentId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Questions).UsePropertyAccessMode(PropertyAccessMode.Field);

            // Adaptive Assessment — Design Proposal §4a.3: a typed record, not
            // a raw JSON string like LessonRevision's TranscriptChaptersJson —
            // this one drives real domain logic (SelectNextAdaptiveQuestion,
            // RecordAdaptiveAnswer, PublicationBlocker), so it stays a real
            // property on Assessment and is only serialized at this boundary.
            entity.Property(e => e.AdaptiveConfiguration)
                  .HasConversion(
                      v => v == null ? null : JsonSerializer.Serialize(v, (JsonSerializerOptions?)null),
                      v => v == null ? null : JsonSerializer.Deserialize<AdaptiveConfiguration>(v, (JsonSerializerOptions?)null))
                  .HasColumnType("text");
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.ToTable("assessment_questions");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Prompt).IsRequired().HasMaxLength(2000);
            entity.Property(e => e.Explanation).HasMaxLength(2000);
            entity.Property(e => e.Type).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.AssessedObjective).HasMaxLength(1000);
            entity.Property(e => e.DifficultyTier).HasConversion<string>().HasMaxLength(32);

            // Small ordered lists owned entirely by this entity — same
            // reasoning as LearningProduct.Tags above, a join table buys nothing.
            // Only one of the two is populated, depending on Type (Question.Apply).
            entity.PrimitiveCollection(e => e.Options);
            entity.PrimitiveCollection(e => e.AcceptedAnswers);
        });

        modelBuilder.Entity<Enrollment>(entity =>
        {
            entity.ToTable("enrollments");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.LearningProductId).IsRequired();
            entity.Property(e => e.MembershipId).IsRequired();

            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // Auto-created on first open (Enrollment.cs remarks) — at most one per (product, membership)
            entity.HasIndex(e => new { e.LearningProductId, e.MembershipId }).IsUnique();
        });

        modelBuilder.Entity<CourseJoinRequest>(entity =>
        {
            entity.ToTable("course_join_requests");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.LearningProductId).IsRequired();
            entity.Property(e => e.MembershipId).IsRequired();

            entity.Property(e => e.Message).HasMaxLength(2000);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // A prior Declined request must not block a fresh one, so the
            // filter (not the index shape) is what changed: at most one
            // Submitted request per (product, membership) is now enforced
            // here too, not just at the service layer's check-then-act.
            entity.HasIndex(e => new { e.LearningProductId, e.MembershipId })
                  .IsUnique()
                  .HasFilter("\"Status\" = 'Submitted'");
        });

        modelBuilder.Entity<Submission>(entity =>
        {
            entity.ToTable("submissions");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            // Nullable as of v1.1 — a Submission references exactly one of
            // AssessmentId or AssignmentId, enforced by the check constraint
            // below (INV-001) and by Start()/StartForAssignment() at the
            // domain layer.
            entity.Property(e => e.AssessmentId);
            entity.Property(e => e.AssignmentId);
            entity.Property(e => e.MembershipId).IsRequired();
            entity.Property(e => e.EnrollmentId).IsRequired();

            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            entity.Property(e => e.AttemptNumber).IsRequired().HasDefaultValue(1);
            entity.Property(e => e.ExcludedFromAttemptCount).IsRequired().HasDefaultValue(false);
            entity.Property(e => e.ResponseText).HasMaxLength(4000);
            entity.Property(e => e.ResponseLearningAssetId);
            entity.Property(e => e.EvaluatorMembershipId);
            entity.Property(e => e.EvaluationMethod).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.Feedback).HasMaxLength(4000);
            entity.Property(e => e.OverrideNote).HasMaxLength(4000);

            // A learner's attempts at one assessment are read together for "latest attempt"
            entity.HasIndex(e => new { e.AssessmentId, e.MembershipId });
            // Same, for the Assignment-target path (v1.1) — also how
            // AssignmentService counts prior attempts for INV-003.
            entity.HasIndex(e => new { e.AssignmentId, e.MembershipId });

            // INV-001: exactly one Target, never both, never neither.
            // Column names are the default EF-generated PascalCase ones
            // (this DbContext doesn't apply a snake_case naming convention),
            // hence the quoted identifiers here.
            entity.ToTable(t => t.HasCheckConstraint(
                "CK_submissions_exactly_one_target",
                "((\"AssessmentId\" IS NOT NULL)::int + (\"AssignmentId\" IS NOT NULL)::int) = 1"));

            entity.HasMany(e => e.Answers).WithOne()
                  .HasForeignKey(a => a.SubmissionId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Answers).UsePropertyAccessMode(PropertyAccessMode.Field);

            entity.HasMany(e => e.CompetencyLevels).WithOne()
                  .HasForeignKey(c => c.SubmissionId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.CompetencyLevels).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<SubmissionAnswer>(entity =>
        {
            entity.ToTable("submission_answers");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.QuestionId).IsRequired();
            entity.Property(e => e.TextAnswer).HasMaxLength(2000);
        });

        modelBuilder.Entity<SubmissionCompetencyLevel>(entity =>
        {
            entity.ToTable("submission_competency_levels");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Objective).IsRequired().HasMaxLength(1000);
            entity.Property(e => e.Level).HasConversion<string>().HasMaxLength(32);
        });

        modelBuilder.Entity<LessonProgress>(entity =>
        {
            entity.ToTable("lesson_progress");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.EnrollmentId).IsRequired();
            entity.Property(e => e.LessonId).IsRequired();
            entity.Property(e => e.LessonRevisionId).IsRequired();

            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // One progress row per (enrollment, lesson)
            entity.HasIndex(e => new { e.EnrollmentId, e.LessonId }).IsUnique();
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.ToTable("notifications");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.MembershipId).IsRequired();
            entity.Property(e => e.LessonId).IsRequired();
            entity.Property(e => e.AssignmentId);
            entity.Property(e => e.Title).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Message).IsRequired().HasMaxLength(2000);
            entity.Property(e => e.Kind).HasConversion<string>().HasMaxLength(64);

            // A learner's own inbox, newest first, and "how many unread" — both read together
            entity.HasIndex(e => new { e.MembershipId, e.CreatedAt });
        });

        modelBuilder.Entity<PlatformOperator>(entity =>
        {
            entity.ToTable("platform_operators");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.IdentityId).IsRequired();

            // Every authorized admin request resolves the caller's grant by IdentityId
            entity.HasIndex(e => e.IdentityId);

            entity.Property(e => e.Status)
                  .HasConversion<string>()
                  .HasMaxLength(32);
        });

        modelBuilder.Entity<WorkspaceRole>(entity =>
        {
            entity.ToTable("workspace_roles");

            entity.HasKey(e => e.Id);

            // Ids are generated by the aggregate, not the database. Without this,
            // EF treats a child added to an already-tracked parent as an existing
            // row (because its key is non-default) and issues an UPDATE that
            // matches nothing.
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Name)
                  .HasConversion<string>()
                  .HasMaxLength(32);

            // A Membership holds a given role at most once
            entity.HasIndex(e => new { e.MembershipId, e.Name }).IsUnique();
        });

        // ── Commercial Domain — core spine (V1a) ────────────────────────────

        modelBuilder.Entity<ConfigurationSnapshot>(entity =>
        {
            entity.ToTable("configuration_snapshots");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.PlanCode).IsRequired().HasMaxLength(64);
            entity.Property(e => e.ProductVersionId).IsRequired();
            entity.Property(e => e.PriceCurrency).IsRequired().HasMaxLength(8);

            entity.Property(e => e.LearningProfile).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.AssessmentProfile).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.AnalyticsProfile).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.BrandingProfile).HasConversion<string>().HasMaxLength(32);

            // Small owned lists — same reasoning as LearningProduct.Tags, a join table buys nothing.
            entity.PrimitiveCollection(e => e.SelectedPackCodes);
            entity.PrimitiveCollection(e => e.SelectedPackVersionIds);

            // A Workspace's snapshot history, newest first — read by Subscription/License lookups
            entity.HasIndex(e => e.WorkspaceId);

            // Resolution (EntitlementResolutionService) loads the exact Version this snapshot was priced against
            entity.HasIndex(e => e.ProductVersionId);
        });

        modelBuilder.Entity<Subscription>(entity =>
        {
            entity.ToTable("subscriptions");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.BillingAccountId).IsRequired();
            entity.Property(e => e.CurrentConfigurationSnapshotId).IsRequired();

            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.BillingCycle).HasConversion<string>().HasMaxLength(32);

            // Cross-aggregate references only (ConfigurationSnapshot, BillingAccount) — no
            // FK constraint, matching the "reference by identifier only" convention used
            // elsewhere between aggregates that evolve independently (e.g. Workspace.OwnerMembershipId).

            // Looking up "this Workspace's current subscription" is the primary access path
            entity.HasIndex(e => e.WorkspaceId);
        });

        modelBuilder.Entity<SubscriptionEvent>(entity =>
        {
            entity.ToTable("subscription_events");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.SubscriptionId).IsRequired();
            entity.Property(e => e.EventType).IsRequired().HasMaxLength(64);
            entity.Property(e => e.ReferenceNote).HasMaxLength(2000);

            // A Subscription's audit trail, read together in order
            entity.HasIndex(e => new { e.SubscriptionId, e.OccurredAt });
        });

        modelBuilder.Entity<WorkspaceLicense>(entity =>
        {
            entity.ToTable("workspace_licenses");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.SubscriptionId).IsRequired();
            entity.Property(e => e.ConfigurationSnapshotId).IsRequired();

            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // One current license per Workspace — Recompute() upserts against this
            entity.HasIndex(e => e.WorkspaceId).IsUnique();

            entity.HasMany(e => e.Entitlements).WithOne()
                  .HasForeignKey(e => e.LicenseId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Entitlements).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<Entitlement>(entity =>
        {
            entity.ToTable("entitlements");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Type).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.Domain).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.Key).IsRequired().HasMaxLength(64);
            entity.Property(e => e.Value).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Source).HasConversion<string>().HasMaxLength(32);

            // Entitlement.source_ref_id is polymorphic (Decision Brief #10, accepted for V1) —
            // no FK constraint, meaning depends on Source.
        });

        modelBuilder.Entity<EntitlementOverride>(entity =>
        {
            entity.ToTable("entitlement_overrides");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.EntitlementKey).IsRequired().HasMaxLength(64);
            entity.Property(e => e.Value).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Reason).IsRequired().HasMaxLength(2000);
            entity.Property(e => e.AppliedByIdentityId).IsRequired();
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // Resolution reads every active override for a Workspace on every recompute
            entity.HasIndex(e => e.WorkspaceId);
        });

        modelBuilder.Entity<BillingAccount>(entity =>
        {
            entity.ToTable("billing_accounts");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();

            // At most one Billing Account per Workspace (lazily created on first checkout)
            entity.HasIndex(e => e.WorkspaceId).IsUnique();
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.ToTable("invoices");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.BillingAccountId).IsRequired();
            entity.Property(e => e.SubscriptionId).IsRequired();
            entity.Property(e => e.ConfigurationSnapshotId).IsRequired();
            entity.Property(e => e.Currency).IsRequired().HasMaxLength(8);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // A Subscription's invoice history, and the overdue sweep's working set
            entity.HasIndex(e => e.SubscriptionId);
            entity.HasIndex(e => e.Status);

            entity.HasMany(e => e.Lines).WithOne()
                  .HasForeignKey(l => l.InvoiceId).OnDelete(DeleteBehavior.Cascade);
            entity.Navigation(e => e.Lines).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        modelBuilder.Entity<InvoiceLine>(entity =>
        {
            entity.ToTable("invoice_lines");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Description).IsRequired().HasMaxLength(256);
            entity.Property(e => e.ComponentType).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.Currency).IsRequired().HasMaxLength(8);
        });

        // ── Commercial Domain — catalog (Products/Packs, database-backed) ───

        modelBuilder.Entity<ProductFamily>(entity =>
        {
            entity.ToTable("product_families");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Code).IsRequired().HasMaxLength(64);
            entity.Property(e => e.Name).IsRequired().HasMaxLength(256);
            entity.HasIndex(e => e.Code).IsUnique();
        });

        modelBuilder.Entity<CommercialProduct>(entity =>
        {
            entity.ToTable("commercial_products");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.ProductFamilyId).IsRequired();
            entity.Property(e => e.Code).IsRequired().HasMaxLength(64);
            entity.Property(e => e.Name).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            // The public catalog and checkout both resolve a plan by its code
            entity.HasIndex(e => e.Code).IsUnique();
        });

        modelBuilder.Entity<CommercialProductVersion>(entity =>
        {
            entity.ToTable("commercial_product_versions");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.ProductId).IsRequired();
            entity.Property(e => e.Currency).IsRequired().HasMaxLength(8);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            entity.Property(e => e.LearningProfile).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.AssessmentProfile).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.AnalyticsProfile).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.BrandingProfile).HasConversion<string>().HasMaxLength(32);

            // "Find this Product's current Published version" — CatalogQueryService's core query
            entity.HasIndex(e => new { e.ProductId, e.Status });
            entity.HasIndex(e => new { e.ProductId, e.VersionNumber }).IsUnique();
        });

        modelBuilder.Entity<CommercialPack>(entity =>
        {
            entity.ToTable("commercial_packs");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Code).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.Name).IsRequired().HasMaxLength(256);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            entity.HasIndex(e => e.Code).IsUnique();
        });

        modelBuilder.Entity<CommercialPackVersion>(entity =>
        {
            entity.ToTable("commercial_pack_versions");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.PackId).IsRequired();
            entity.Property(e => e.Currency).IsRequired().HasMaxLength(8);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);

            entity.Property(e => e.LearningGrant).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.AssessmentGrant).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.AnalyticsGrant).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.BrandingGrant).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.RequiresDomain).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.RequiresMinLevel).HasConversion<string>().HasMaxLength(32);

            entity.HasIndex(e => new { e.PackId, e.Status });
            entity.HasIndex(e => new { e.PackId, e.VersionNumber }).IsUnique();
        });

        modelBuilder.Entity<CreditLedgerEntry>(entity =>
        {
            entity.ToTable("credit_ledger_entries");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.EntryType).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.SkillKey).HasMaxLength(128);
            entity.Property(e => e.IdempotencyFingerprint).HasMaxLength(64); // hex-encoded SHA-256

            // GetBalanceAsync sums every non-expired row for a workspace on
            // (effectively) every AI-assist call — the hot path this ledger exists for.
            entity.HasIndex(e => new { e.WorkspaceId, e.ExpiresAtUtc });

            // CreditLedgerService.TryDebitAsync's retry-dedup lookup — not
            // unique, since the same fingerprint legitimately recurs once the
            // dedup time window has passed (see IdempotencyFingerprint's doc).
            entity.HasIndex(e => new { e.WorkspaceId, e.IdempotencyFingerprint });
        });

        modelBuilder.Entity<SkillCreditCost>(entity =>
        {
            entity.ToTable("skill_credit_costs");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.SkillKey).IsRequired().HasMaxLength(128);

            // TryDebitAsync's price lookup: current row for a (SkillKey, Band).
            entity.HasIndex(e => new { e.SkillKey, e.Band, e.EffectiveFrom });
        });

        modelBuilder.Entity<CreditPurchaseOrder>(entity =>
        {
            entity.ToTable("credit_purchase_orders");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.WorkspaceId).IsRequired();
            entity.Property(e => e.CreditPackCode).IsRequired().HasMaxLength(64);
            entity.Property(e => e.PriceCurrency).IsRequired().HasMaxLength(8);
            entity.Property(e => e.Status).HasConversion<string>().HasMaxLength(32);
            entity.Property(e => e.RequestedByIdentityId).IsRequired();
            entity.Property(e => e.ReferenceNote).HasMaxLength(2000);

            // A workspace's own purchase history
            entity.HasIndex(e => e.WorkspaceId);
            // The admin console's pending-requests list
            entity.HasIndex(e => e.Status);
        });
    }
}
